# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
swift_version = '3.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'synapsewear' do
    pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git'
    #pod 'AlamofireImage', :git => 'https://github.com/Alamofire/AlamofireImage.git'
    #pod 'AFNetworking'
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
    pod 'F53OSC', :git => 'https://github.com/Figure53/F53OSC.git'
end

target 'synapsewearTests' do

end

target 'synapsewearUITests' do

end

